create procedure Delete_null_testing_capacity AS
DELETE  LSS.dbo.Dash_Testing_Capacity
  where (Date is null or Date='')
      and ( Name_of_Lab    is null or  Name_of_Lab     is null)
      and ( Test_Type='' or Test_Type     is null)
      and ( Platform_Roche_Abbott_Hologic_BMX='' or Platform_Roche_Abbott_Hologic_BMX    is null)
      and ( Target_Weekly_assigned='' or Target_Weekly_assigned    is null)
      and ( VALID_Weekly_Tests_done='' or VALID_Weekly_Tests_done    is null)
      and ( TEST_to_HIT_Weekly_Targets='' or TEST_to_HIT_Weekly_Targets    is null)
      and ( NatPharm_Kits_Received_inThisWK='' or NatPharm_Kits_Received_inThisWK    is null)
      and ( Date_Received_at_Lab='' or Date_Received_at_Lab    is null)
      and ( Reagent_kits_to_OTHER_Labs='' or Reagent_kits_to_OTHER_Labs    is null)
      and ( Lab_Name_Loaned_to='' or Lab_Name_Loaned_to    is null)
      and ( Reagents_Transported_ConsgnNum='' or Reagents_Transported_ConsgnNum    is null)
      and ( Reagent_kits_RECEIVED_from_OTHER_Labs='' or Reagent_kits_RECEIVED_from_OTHER_Labs    is null)
      and ( Lab_Name_Received_from='' or Lab_Name_Received_from    is null)
      and ( Reagent_tests_kits_Stock_on_hand ='' or Reagent_tests_kits_Stock_on_hand    is null)
      and ( Reagent_tests_kits_available='' or Reagent_tests_kits_available    is null)
      and ( Reagent_tests_kits_available_Batch_lot_Number='' or Reagent_tests_kits_available_Batch_lot_Number    is null)
      and ( Reagent_tests_kits_available_Expiry_Date='' or Reagent_tests_kits_available_Expiry_Date    is null)
      and ( Reagent_stockout_days='' or Reagent_stockout_days    is null)
      and ( Tests_expired_this_month_before_use='' or Tests_expired_this_month_before_use    is null)
      and ( Cost_of_transportation='' or Cost_of_transportation    is null)
      and ( Comments_Reagent_Stock_Status='' or Comments_Reagent_Stock_Status    is null)