CREATE PROCEDURE  [Delete_creation_duplicates] AS 

WITH CTE AS (
    SELECT *,
           ROW_NUMBER() OVER(PARTITION BY [Sample_ID]
      ,[Client_Sample_ID]
      ,[Testing_Lab]
      ,[Referring_Lab]
      ,[Province]
      ,[District]
      ,[Facility]
      ,[Client_Contact]
      ,[Client_Patient_ID]
      ,[Patient_Name]
      ,[Sex]
      ,[DOB]
      ,[Age]
      ,[Breast_Feeding]
      ,[Pregnant]
      ,[Reason]
      ,[Regimen]
      ,[HIV_Status]
      ,[Reason_For_TB_Exam]
      ,[Requested_By]
      ,[Date_Sampled]
      ,[Date_Registered]
      ,[Date_Received]
      ,[Date_Received_at_Hub]
      ,[Date_Rejected]
      ,[Creator]
      ,[Date_of_Testing]
      ,[Date_of_Dispatch]
      ,[Date_Printed]
      ,[Print_Location]
      ,[Registration_Location]
      ,[Analysis_Profile]
      ,[Category]
      ,[Method]
      ,[Test]
      ,[Result]
      ,[Comment]
      ,[Analyst]
      ,[Verifier]
      ,[Review_State]
      ,[Retest]
      ,[Rejection_Reasons]
      ,[SourceFile] ORDER BY (SELECT NULL)) AS rn
    FROM [LSS].[dbo].[Creation_Reports_Hub_Lab]
)
DELETE FROM CTE WHERE rn > 1;