CREATE TABLE [dbo].[Dash_Lab_Metrics_Waste_Mgt] (
    [Date]                                    VARCHAR (255) NULL,
    [Name_of_Lab]                             VARCHAR (255) NULL,
    [Test_Type]                               VARCHAR (255) NULL,
    [Platform_Roche_Abbott_Hologic_BMX]       VARCHAR (255) NULL,
    [Weekly_8hour_test_capacity]              INT           NULL,
    [Planned_number_ofdays_platform_used]     INT           NULL,
    [Actual_number_of_days_platform_used]     INT           NULL,
    [Weekly_planned_number_of_tests]          INT           NULL,
    [Num_Machine_Breakdowns]                  INT           NULL,
    [Hrs_in_Shift]                            INT           NULL,
    [Downtime_Power_Outage]                   INT           NULL,
    [Downtime_Mechanical_Failure]             INT           NULL,
    [Downtime_Reagent_Stockout_Expiry]        INT           NULL,
    [Downtime_Staff_Unavailability]           INT           NULL,
    [Total_Operational_Hrs]                   INT           NULL,
    [Tests_tobe_Done_Received&Carryover]      INT           NULL,
    [Tests_Successfuly_completed]             INT           NULL,
    [Amt_of_Liquid_Waste_ltrs]                INT           NULL,
    [Comments_on_ErrorCodes_for_Mach_failure] VARCHAR (MAX) NULL,
    [SourceFile]                              VARCHAR (255) NULL,
    [Update_date]                             DATE          DEFAULT (getdate()) NULL,
    [unique_key]                              VARCHAR (255) NULL,
    [Downtime_Controls_Stockout_Expiry]       VARCHAR (255) NULL,
    [Downtime_Controls_Failure]               VARCHAR (255) NULL,
    [Downtime_coz_other_reasons]              VARCHAR (255) NULL,
    [Status]                                  VARCHAR (255) NULL,
    [Machine_Capacity_Modules]                VARCHAR (255) NULL,
    [Number_of_functional_modules]            VARCHAR (255) NULL,
    [checked]                                 VARCHAR (255) NULL
);

