CREATE TABLE [dbo].[Dash_Referred_Samples] (
    [Date]                                   VARCHAR (255)  NULL,
    [Name_of_Lab]                            VARCHAR (255)  NULL,
    [Sample_Type]                            VARCHAR (255)  NULL,
    [Test_Type]                              VARCHAR (255)  NULL,
    [Samples_reffered_Out]                   INT            NULL,
    [Lab_Samples_referred_to]                VARCHAR (255)  NULL,
    [Referred_Sample_Received]               INT            NULL,
    [CARRYOVER_Referred_Sample_Received]     INT            NULL,
    [NOT_CARRYOVER_Referred_Sample_Received] INT            NULL,
    [Referred_From]                          VARCHAR (255)  NULL,
    [URGENT_Referred_Samples]                INT            NULL,
    [REBLEED_Referred_Samples]               INT            NULL,
    [REJECTED_Referred_Samples]              INT            NULL,
    [REFERRED_Reagent_Stockout]              INT            NULL,
    [REFERRED_Instrument_Failure]            INT            NULL,
    [REFERRED_Insuff_HR_Capacity]            INT            NULL,
    [REFERRED_Insuff_Instrument_Capacity]    INT            NULL,
    [Samples_Captured_thru_LIMS]             INT            NULL,
    [Comments]                               NVARCHAR (MAX) NULL,
    [SourceFile]                             VARCHAR (255)  NULL,
    [Update_Date]                            DATE           DEFAULT (getdate()) NULL,
    [unique_key]                             VARCHAR (255)  NULL,
    [Data_Quality_Checks]                    VARCHAR (255)  NULL,
    [REFERRED_Other_rexns]                   VARCHAR (255)  NULL,
    [Status]                                 VARCHAR (255)  NULL,
    [REFERRED_before_captured_LIMS]          VARCHAR (255)  NULL,
    [id]                                     INT            IDENTITY (1, 1) NOT NULL,
    [Swift_Consignment_Number]               VARCHAR (255)  NULL
);

