CREATE TABLE [dbo].[Dashboard_Indicators] (
    [LAB]                                                   VARCHAR (255) NULL,
    [Number_of_carryover_samples]                           INT           NULL,
    [Backlog]                                               INT           NULL,
    [Age_of_oldest_Plasma_sample]                           INT           NULL,
    [Age_of_oldest_DBS_sample]                              INT           NULL,
    [Age_of_oldest_EID_sample]                              INT           NULL,
    [Number_of_samples_received_this_week]                  INT           NULL,
    [Total_received_samples_with_Age_Sex_Disaggregation]    INT           NULL,
    [Number_of_samples_that_are_rejected]                   INT           NULL,
    [Total_with_reasons_for_rejection]                      INT           NULL,
    [Number_of_samples_entered_into_LIMS_on_day_of_arrival] INT           NULL,
    [Total_number_of_referred_samples_received]             INT           NULL,
    [Total_referred_with_reason_for_referral]               INT           NULL,
    [Total_number_of_samples_run]                           INT           NULL,
    [Calculated_carryover_at_start_of_week_Plasma_VL]       INT           NULL,
    [Calculated_carryover_at_start_of_week_DBS_VL]          INT           NULL,
    [Calculated_carryover_at_start_of_week_DBS_EID]         INT           NULL,
    [Total_number_failed_eligible_for_repeat]               INT           NULL,
    [Total_number_failed_not_eligible_for_repeat]           INT           NULL,
    [Number_with_reason_for_failure]                        INT           NULL,
    [Number_of_results_printed_from_LIMS_by_VL_Lab]         INT           NULL,
    [Number_of_results_dispatched_by_lab]                   INT           NULL,
    [Reagent_test_kits_available]                           INT           NULL,
    [Total_machine_downtime_hours]                          INT           NULL,
    [LIMS_Hours_of_functionality]                           INT           NULL,
    [Number_of_hours_with_no_electricity]                   INT           NULL,
    [Number_of_hours_generator_was_on]                      INT           NULL,
    [Update_Date]                                           DATE          DEFAULT (getdate()) NULL,
    [SourceFile]                                            VARCHAR (255) NULL,
    [Date]                                                  VARCHAR (50)  NULL,
    [unique_key]                                            VARCHAR (255) NULL,
    [Status]                                                VARCHAR (255) NULL
);

