CREATE TABLE [dbo].[Dash_Age_Sex_Disaggregation] (
    [Date]                 VARCHAR (255)  NULL,
    [Name_of_Lab]          VARCHAR (255)  NULL,
    [Males_<15]            INT            NULL,
    [Males_15_19]          INT            NULL,
    [Males_20_24]          INT            NULL,
    [Males_25_49]          INT            NULL,
    [Males_>50]            INT            NULL,
    [Males_Unknown]        INT            NULL,
    [Fem_Non_PBFW_<15]     INT            NULL,
    [Fem_Non_PBFW_15_19]   INT            NULL,
    [Fem_Non_PBFW_20_24]   INT            NULL,
    [Fem_Non_PBFW_25_49]   INT            NULL,
    [Fem_Non_PBFW_>50]     INT            NULL,
    [Fem_Non_PBFW_Unknown] INT            NULL,
    [Female_PBFW_<15]      INT            NULL,
    [Female_PBFW_15_19]    INT            NULL,
    [Female_PBFW_20_24]    INT            NULL,
    [Female_PBFW_25_49]    INT            NULL,
    [Female_PBFW_>50]      INT            NULL,
    [Female_PBFW_Unknown]  INT            NULL,
    [Unknown_Sex_<15]      INT            NULL,
    [Unknown_Sex_15_19]    INT            NULL,
    [Unknown_Sex_20_24]    INT            NULL,
    [Unknown_Sex_25_49]    INT            NULL,
    [Unknown_Sex_>50]      INT            NULL,
    [Unknown_Sex_Unknown]  INT            NULL,
    [Comments]             NVARCHAR (MAX) NULL,
    [SourceFile]           VARCHAR (255)  NULL,
    [Update_Date]          DATE           DEFAULT (getdate()) NULL,
    [unique_key]           VARCHAR (255)  NULL,
    [checked]              VARCHAR (255)  NULL
);

