CREATE TABLE [dbo].[Dash_CLI] (
    [Date]                                                           VARCHAR (255)  NULL,
    [Name_of_Lab]                                                    VARCHAR (255)  NULL,
    [ReBLEEDs_requests_sent]                                         INT            NULL,
    [Incidents_nid_Comms_btwn_LAB_CLINICS]                           INT            NULL,
    [Number_of_correspondences]                                      INT            NULL,
    [Post_Corresp_nid_Followups]                                     INT            NULL,
    [Action_items_performed]                                         INT            NULL,
    [LAST_WEEK_Unresolved_missing_results]                           INT            NULL,
    [THIS_WEEK_Missing_results_req_by_Facilities]                    INT            NULL,
    [RESOLVED_Missing_results_outcomes_found_Shared_with_facilities] INT            NULL,
    [RESOLVED_LIMS_Interface_Failed]                                 INT            NULL,
    [RESOLVED_Results_not_documented_at_facility]                    INT            NULL,
    [RESOLVED_Results_sent_to_wrong_facility]                        INT            NULL,
    [RESOLVED_Results_not_yet_dispatched_printed]                    INT            NULL,
    [RESOLVED_Specimens_not_received_rebleed_sent]                   INT            NULL,
    [RESOLVED_Specimens_rejected]                                    INT            NULL,
    [RESOLVED_Result_pending_publishing]                             INT            NULL,
    [UNRESOLVED_Pending_testing]                                     INT            NULL,
    [UNRESOLVED_Referred_awaiting_results]                           INT            NULL,
    [UNRESOLVED_Investigation_in_progress]                           INT            NULL,
    [Comments]                                                       NVARCHAR (MAX) NULL,
    [SourceFile]                                                     VARCHAR (255)  NULL,
    [Update_date]                                                    DATE           DEFAULT (getdate()) NULL,
    [Unnamed: 21]                                                    VARCHAR (255)  NULL,
    [unique_key]                                                     VARCHAR (255)  NULL,
    [Result_transmission_to_hub_failed]                              VARCHAR (255)  NULL,
    [Corrsp_test_requests_clinic_clarificatons]                      VARCHAR (255)  NULL,
    [Corrsp_clinic_send_spec_to_diff_lab]                            VARCHAR (255)  NULL,
    [Corrsp_clinic_expect_delay_due_lab_stockouts]                   VARCHAR (255)  NULL,
    [Corrsp_clinic_halt_spec_collection_due_lab_stockouts]           VARCHAR (255)  NULL,
    [Status]                                                         VARCHAR (255)  NULL,
    [Corrsp_clinic_adjust_algorith_stockouts]                        VARCHAR (255)  NULL,
    [checked]                                                        VARCHAR (255)  NULL
);

