CREATE TABLE [dbo].[EID] (
    [Sample ID]             NVARCHAR (255) NULL,
    [Client Sample ID]      NVARCHAR (255) NULL,
    [Testing Lab]           NVARCHAR (255) NULL,
    [Referring Lab]         NVARCHAR (255) NULL,
    [Province]              NVARCHAR (255) NULL,
    [District]              NVARCHAR (255) NULL,
    [Facility]              NVARCHAR (255) NULL,
    [Client Contact]        NVARCHAR (255) NULL,
    [Client Patient ID]     NVARCHAR (255) NULL,
    [Patient Name]          NVARCHAR (255) NULL,
    [Sex]                   NVARCHAR (255) NULL,
    [DOB]                   NVARCHAR (255) NULL,
    [Age]                   NVARCHAR (255) NULL,
    [Breast Feeding]        NVARCHAR (255) NULL,
    [Pregnant]              NVARCHAR (255) NULL,
    [Reason]                NVARCHAR (255) NULL,
    [Regimen]               NVARCHAR (255) NULL,
    [HIV Status]            NVARCHAR (255) NULL,
    [Reason For TB Exam]    NVARCHAR (255) NULL,
    [Requested By]          NVARCHAR (255) NULL,
    [Date Sampled]          NVARCHAR (255) NULL,
    [Date Registered]       NVARCHAR (255) NULL,
    [Date Received]         NVARCHAR (255) NULL,
    [Date Received at Hub]  NVARCHAR (255) NULL,
    [Date Rejected]         NVARCHAR (255) NULL,
    [Creator]               NVARCHAR (255) NULL,
    [Date of Testing]       NVARCHAR (255) NULL,
    [Date of Dispatch]      NVARCHAR (255) NULL,
    [Date Printed]          NVARCHAR (255) NULL,
    [Print Location]        NVARCHAR (255) NULL,
    [Registration Location] NVARCHAR (255) NULL,
    [Analysis Profile]      NVARCHAR (255) NULL,
    [Category]              NVARCHAR (255) NULL,
    [Method]                NVARCHAR (255) NULL,
    [Test]                  NVARCHAR (255) NULL,
    [Result]                NVARCHAR (255) NULL,
    [Comment]               NVARCHAR (255) NULL,
    [Analyst]               NVARCHAR (255) NULL,
    [Verifier]              NVARCHAR (255) NULL,
    [Review State]          NVARCHAR (255) NULL,
    [Retest]                NVARCHAR (255) NULL,
    [Rejection Reasons]     NVARCHAR (255) NULL,
    [f43]                   NVARCHAR (255) NULL
);

